services:
  postgres_dev:
    image: postgres:18.0
    restart: "no"
    volumes:
      - twp_dev_postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432

  cronjobs_dev:
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - FOWNER
      - SETUID
      - SETGID
    tmpfs:
      - /tmp:mode=1777
      - /build/prometheus_multi_proc_dir:mode=0775,uid=2222,gid=0
    restart: "no"
    build:
      target: build
      context: ./
    ports:
      - 8052:8050
    command: /build/scripts/init_cronjobs.sh
    environment:
      - POSTGRES_HOST=postgres_dev
      - DEBUG_TOOLBAR=0
    env_file:
      - .env
    volumes:
      - "disk_cache:/build/disk_cache"
      - "default_disk_cache:/build/default_disk_cache"
      - "logs:/build/logs"
      - "media:/build/media"

  web_dev:
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - FOWNER
      - SETUID
      - SETGID
    tmpfs:
      - /tmp:mode=1777
      - /build/prometheus_multi_proc_dir:mode=0775,uid=2222,gid=0
    depends_on:
      - postgres_dev
    restart: "no"
    build:
      target: build
      context: ./
    ports:
      - 7998:80
      - 8053:8050
    env_file:
      - .env
    environment:
      - DEBUG=false
      - SECRET_KEY=askldjasd0987123987
      - SUB_DOMAIN=web
      - CSRF_TRUSTED_ORIGIN=http://localhost:7998
      - POSTGRES_HOST=postgres_dev
      - DEBUG_TOOLBAR=0
    volumes:
      - "disk_cache:/build/disk_cache"
      - "default_disk_cache:/build/default_disk_cache"
      - "logs:/build/logs"
      - "media:/build/media"

volumes:
  twp_dev_postgresql:
  disk_cache:
  default_disk_cache:
  logs:
  media:
