FROM nginx/unit:1.23.0-python3.9

ENV PYTHONUNBUFFERED 1

COPY ./initial.sh /docker-entrypoint.d/initial.sh
COPY ./config/config.json /docker-entrypoint.d/config.json

RUN mkdir build

WORKDIR /build

RUN apt-get update                        \
    && apt-get install -y python3-pip

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

RUN mkdir media
RUN chmod +w media
