services:
  postgres_dev:
    image: postgres:16.1
    restart: "no"
    volumes:
      - twp_dev_postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432

  cronjobs_dev:
    restart: "no"
    build:
      target: build
      context: ./
    ports:
      - 8052:8050
    command: /build/scripts/init_cronjobs.sh
    environment:
      - POSTGRES_HOST=postgres_dev
    env_file:
      - .env

  web_dev:
    depends_on:
      - postgres_dev
    restart: "no"
    build:
      target: build
      context: ./
    ports:
      - 7998:80
      - 8053:8050
    env_file:
      - .env
    environment:
      - DEBUG=false
      - SECRET_KEY=askldjasd0987123987
      - SUB_DOMAIN=web
      - CSRF_TRUSTED_ORIGIN=http://localhost:7998
      - POSTGRES_HOST=postgres_dev

volumes:
  twp_dev_postgresql:
