FROM python:3.11.1-bullseye

RUN apt-get update
RUN apt-get install gettext -y

RUN mkdir app
WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

CMD python manage.py makemessages --all --ignore .venv &&  \
    python manage.py compilemessages --ignore .venv