FROM python:3.9.6-buster

RUN apt-get update
RUN apt-get install cron -y

RUN mkdir app
WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

RUN python manage.py crontab add  && \
    python manage.py crontab show && \
    service cron restart

CMD cron -f
