FROM python:3.9.6-buster

RUN apt-get update
RUN apt-get install gettext -y

RUN mkdir app
WORKDIR /app

COPY . .
RUN pip install -r requirements.txt

CMD python manage.py makemessages --all --ignore .venv &&  \
    python manage.py compilemessages --ignore .venv