# Generated by Django 5.1.8 on 2025-05-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
