site_name: "Planejador de Guerras Tribais"
site_url: "https://plemiona-planer.pl/pt-br/documentation/"
docs_dir: "../../docs/pt-br"
site_dir: "../../../generated_docs/pt-br/documentation"
repo_url: https://github.com/rafsaf/Tribal-Wars-Planer
edit_uri: "edit/master/docs/docs/pt-br"

theme:
  palette:
    primary: teal
  features:
    - navigation.tabs
    - navigation.top
    - navigation.path
    - navigation.sections
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.action.edit
    - navigation.footer
  name: material
  custom_dir: "../../overrides/"
  logo: assets/images/favicon.jpg
  favicon: assets/images/favicon.jpg
  language: pt

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rafsaf/Tribal-Wars-Planer
    - icon: fontawesome/brands/discord
      link: https://discord.gg/g5pcsCteCT
  alternate:
    - name: Polski
      link: /pl/documentation/
      lang: pl
    - name: English
      link: /en/documentation/
      lang: en
    - name: Magyar
      link: /hu/documentation/
      lang: hu
    - name: Português (Brasil)
      link: /pt-br/documentation/
      lang: pt-br
    - name: Česky
      link: /cs/documentation/
      lang: cs

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
      base_path:
        - ./docs/overrides/data/
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search:
      lang: pt
  - glightbox
  - social

nav:
  - Voltar à página: "/"
  - FAQ: index.md
  - 1. Mundo de teste:
      - first_steps/index.md
      - "Passo 1: Criar um plano": first_steps/step_1_create_outline.md
      - "Passo 2: Escolher tribos": first_steps/step_2_choose_tribes.md
      - "Passo 3: Preencher dados": first_steps/step_3_fill_data.md
      - "Passo 4: Salvar alvos e configurações": first_steps/step_4_save_targets_and_settings.md
      - "Passo 5: Edição do plano": first_steps/step_5_outline_edit.md
      - "Passo 6: Definir hora de conclusão": first_steps/step_6_set_time_finish.md
      - "Passo 7: Aba de resultados": first_steps/step_7_results_tab.md
  - 2. Instalação dos scripts necessários:
      - "Coleta de exército e defesa": scripts/army_and_defence_collection.md
      - "Envio de mensagens": scripts/sending_messages.md
  - 3. Guias:
      - "Escrever alvos do plano": primary/write_outline_targets.md
      - "Duas regiões da tribo": primary/two_regions_of_the_tribe.md
      - "Planos pequenos": primary/small_outlines.md
      - "Planos médios": primary/medium_outlines.md
      - "Planos grandes": primary/large_outlines.md
      - "Planos de ruína": primary/ruin_outlines.md
  - 4. Avançado:
      - "Tropas disponíveis e tabela": advanced/1_available_troops_and_table.md
      - "Mudança de data": advanced/2_change_of_date.md
      - "Parâmetros do plano": advanced/3_outline_parameters.md
      - "Moral": advanced/4_morale.md
      - "Evitar bônus noturno": advanced/5_avoid_night_bonus.md
      - "Ruína": advanced/6_ruin.md
  - API Pública:
      - developers/index.md
