# Generated by Django 3.0.7 on 2020-12-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="initial_outline_excluded_coords",
            field=models.TextField(default=""),
        ),
    ]
