# Generated by Django 3.0.6 on 2020-05-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_outline',
            name='swiat',
            field=models.CharField(max_length=6),
        ),
    ]
