# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 3.0.7 on 2020-12-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_outline_initial_outline_excluded_coords"),
    ]

    operations = [
        migrations.AddField(
            model_name="overview",
            name="deputy",
            field=models.TextField(default=""),
        ),
    ]
