# Generated by Django 3.0.6 on 2020-05-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200527_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_outline',
            name='swiat',
            field=models.CharField(choices=[], max_length=6),
        ),
    ]
