# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 3.0.7 on 2020-12-16 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_overview_deputy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outline",
            name="initial_outline_front_dist",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(45),
                ],
            ),
        ),
    ]
