# Generated by Django 3.0.6 on 2020-05-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200527_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_outline',
            name='swiat',
            field=models.CharField(choices=[('150', '150'), ('150', '150')], max_length=6),
        ),
    ]
