# Generated by Django 3.0.6 on 2020-05-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200527_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_outline',
            name='swiat',
            field=models.CharField(choices=[('153', '153'), ('150', '150')], max_length=6),
        ),
    ]
