# Generated by Django 3.0.6 on 2020-05-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200527_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_outline',
            name='swiat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
