# Copyright 2021 Rafał Safin (rafsaf). All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# Generated by Django 3.0.7 on 2021-01-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_auto_20210120_2128"),
    ]

    operations = [
        migrations.AddField(
            model_name="outlineoverview",
            name="targets_json",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="outlineoverview",
            name="weights_json",
            field=models.TextField(blank=True, default=""),
        ),
    ]
