# Generated by Django 3.0.6 on 2020-06-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200527_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_outline',
            name='moje_plemie_skrot',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='new_outline',
            name='przeciwne_plemie_skrot',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
