# Generated by Django 3.0.7 on 2021-01-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_auto_20210120_2128"),
    ]

    operations = [
        migrations.AddField(
            model_name="outlineoverview",
            name="targets_json",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="outlineoverview",
            name="weights_json",
            field=models.TextField(blank=True, default=""),
        ),
    ]
