# Copyright 2021 Rafał Safin (rafsaf). All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# Generated by Django 3.0.7 on 2021-02-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_auto_20210127_2222"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="enter_t1",
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name="outline",
            name="enter_t2",
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name="outline",
            name="night_bonus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="targetvertex",
            name="enter_t1",
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name="targetvertex",
            name="enter_t2",
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name="targetvertex",
            name="night_bonus",
            field=models.BooleanField(default=False),
        ),
    ]
