# Generated by Django 3.0.7 on 2021-02-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_auto_20210127_2222"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="enter_t1",
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name="outline",
            name="enter_t2",
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name="outline",
            name="night_bonus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="targetvertex",
            name="enter_t1",
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name="targetvertex",
            name="enter_t2",
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name="targetvertex",
            name="night_bonus",
            field=models.BooleanField(default=False),
        ),
    ]
