# Generated by Django 3.0.6 on 2020-06-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20200601_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_outline',
            name='data_akcji',
            field=models.DateField(blank=True, null=True),
        ),
    ]
