# Generated by Django 3.0.6 on 2020-06-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20200601_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='speed_units',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='world',
            name='speed_world',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='new_outline',
            name='zbiorka_obrona',
            field=models.TextField(blank=True, default='', help_text="Wymagana dokładna forma ze skryptu Obrona, zajrzyj do <a href='/dokumentacja'>dokumentacji</a>", null=True),
        ),
        migrations.AlterField(
            model_name='new_outline',
            name='zbiorka_wojsko',
            field=models.TextField(blank=True, default='', help_text="Wymagana dokładna forma ze skryptu Wojska, zajrzyj do <a href='/dokumentacja'>dokumentacji</a>", null=True),
        ),
    ]
