# Generated by Django 3.0.7 on 2021-02-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_auto_20210218_1528"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightmodel",
            name="t1",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="weightmodel",
            name="t2",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
