# Generated by Django 3.0.6 on 2020-06-05 19:15

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_documentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='main_page',
            field=markdownx.models.MarkdownxField(default='x'),
            preserve_default=False,
        ),
    ]
