# Generated by Django 3.0.7 on 2021-05-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_auto_20210407_1633"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="choice_sort",
            field=models.CharField(
                choices=[
                    ("distance", "distance"),
                    ("random_distance", "random_distance"),
                    ("-distance", "-distance"),
                    ("-off_left", "-off_left"),
                    ("-nobleman_left", "-nobleman_left"),
                    ("closest_offs", "closest_offs"),
                    ("random_offs", "random_offs"),
                    ("farthest_offs", "farthest_offs"),
                    ("closest_noblemans", "closest_noblemans"),
                    ("random_noblemans", "random_noblemans"),
                    ("farthest_noblemans", "farthest_noblemans"),
                    ("closest_noble_offs", "closest_noble_offs"),
                    ("random_noble_offs", "random_noble_offs"),
                    ("farthest_noble_offs", "farthest_noble_offs"),
                ],
                default="distance",
                max_length=50,
            ),
        ),
    ]
