# Copyright 2021 Rafał Safin (rafsaf). All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# Generated by Django 3.0.7 on 2021-05-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_auto_20210407_1633"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="choice_sort",
            field=models.CharField(
                choices=[
                    ("distance", "distance"),
                    ("random_distance", "random_distance"),
                    ("-distance", "-distance"),
                    ("-off_left", "-off_left"),
                    ("-nobleman_left", "-nobleman_left"),
                    ("closest_offs", "closest_offs"),
                    ("random_offs", "random_offs"),
                    ("farthest_offs", "farthest_offs"),
                    ("closest_noblemans", "closest_noblemans"),
                    ("random_noblemans", "random_noblemans"),
                    ("farthest_noblemans", "farthest_noblemans"),
                    ("closest_noble_offs", "closest_noble_offs"),
                    ("random_noble_offs", "random_noble_offs"),
                    ("farthest_noble_offs", "farthest_noble_offs"),
                ],
                default="distance",
                max_length=50,
            ),
        ),
    ]
