# Generated by Django 3.0.6 on 2020-06-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_documentation_main_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='title',
            field=models.CharField(default='Spis_tresci', max_length=10),
            preserve_default=False,
        ),
    ]
