# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 3.2.2 on 2021-05-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0013_outline_simple_textures"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="PLN", max_length=3),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.FloatField(),
        ),
    ]
