# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 3.2.2 on 2021-05-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0015_auto_20210522_1245"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightmaximum",
            name="too_far_away",
            field=models.BooleanField(default=False),
        ),
    ]
