# Generated by Django 3.2.2 on 2021-05-23 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20210524_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outline',
            name='initial_outline_target_dist',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
