# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 3.2.3 on 2021-06-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0018_alter_outline_initial_outline_target_dist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="currency",
        ),
        migrations.AddField(
            model_name="payment",
            name="event_id",
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
