# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 3.2.3 on 2021-06-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0019_auto_20210601_2112"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outline",
            name="filter_hide_front",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("front", "Front"),
                    ("back", "Back (Rear)"),
                    ("away", "Away"),
                    ("hidden", "Hidden"),
                ],
                default="all",
                max_length=20,
            ),
        ),
    ]
