# Generated by Django 3.2.3 on 2021-06-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_outline_filter_hide_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='from_stripe',
            field=models.BooleanField(default=False),
        ),
    ]
