# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 3.2.3 on 2021-06-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0021_payment_from_stripe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outline",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
