# Generated by Django 3.2.3 on 2021-06-12 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20210612_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outline_pk', models.IntegerField()),
                ('owner_name', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('world', models.CharField(max_length=50)),
                ('premium_user', models.BooleanField()),
                ('off_troops', models.IntegerField(default=0)),
                ('deff_troops', models.IntegerField(default=0)),
                ('real_targets', models.IntegerField(default=0)),
                ('fake_targets', models.IntegerField(default=0)),
                ('ruin_targets', models.IntegerField(default=0)),
                ('troops_refreshed', models.IntegerField(default=0)),
                ('outline_written', models.IntegerField(default=0)),
                ('available_troops', models.IntegerField(default=0)),
                ('date_change', models.IntegerField(default=0)),
                ('settings_change', models.IntegerField(default=0)),
                ('night_change', models.IntegerField(default=0)),
                ('ruin_change', models.IntegerField(default=0)),
                ('building_order_change', models.IntegerField(default=0)),
                ('time_created', models.IntegerField(default=0)),
                ('go_back_clicked', models.IntegerField(default=0)),
                ('finish_outline_clicked', models.IntegerField(default=0)),
                ('overview_visited', models.IntegerField(default=0)),
                ('outline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.outline')),
            ],
        ),
    ]
