# Generated by Django 3.2.4 on 2021-06-30 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0024_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="filter_weights_catapults_min",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3000),
                ],
            ),
        ),
    ]
