# Generated by Django 3.2.5 on 2021-07-03 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_outline_filter_weights_catapults_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightmaximum',
            name='outline',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='base.outline'),
        ),
        migrations.AlterField(
            model_name='weightmaximum',
            name='start',
            field=models.CharField(max_length=7),
        ),
    ]
