# Generated by Django 3.2.7 on 2021-09-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20210827_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightmodeloverview',
            name='target',
        ),
        migrations.DeleteModel(
            name='TargetVertexOverview',
        ),
        migrations.DeleteModel(
            name='WeightModelOverview',
        ),
    ]
