# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 3.2.7 on 2021-11-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0028_auto_20210919_2030"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFPaymentSummary",
            fields=[
                (
                    "period",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("path", models.CharField(max_length=300)),
            ],
        ),
    ]
