# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 3.2.7 on 2021-12-17 21:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0029_pdfpaymentsummary"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Documentation",
        ),
    ]
