# Generated by Django 3.2.7 on 2021-12-17 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_pdfpaymentsummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documentation',
        ),
    ]
