# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 3.2.11 on 2022-01-08 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0030_delete_documentation"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="server_bind",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="server_bind_remind_not_before_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
