# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 3.2.11 on 2022-01-08 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0031_auto_20220108_1915"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="server_bind_remind_not_before_date",
        ),
    ]
