# Generated by Django 4.0.2 on 2022-02-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0033_outline_initial_outline_max_off"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="villages",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="world",
            name="etag",
            field=models.CharField(default="", max_length=200),
        ),
    ]
