# Generated by Django 4.0.2 on 2022-02-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0034_outline_morale_on_targets_greater_than_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="morale_on",
            field=models.BooleanField(default=True),
        ),
    ]
