# Generated by Django 4.0.2 on 2022-02-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0034_player_points_player_villages_world_etag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="world",
            old_name="etag",
            new_name="etag_player",
        ),
        migrations.AddField(
            model_name="world",
            name="etag_tribe",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="world",
            name="etag_village",
            field=models.CharField(default="", max_length=200),
        ),
    ]
