# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 4.0.2 on 2022-03-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0037_profile_default_morale_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetvertex",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weightmaximum",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
