# Copyright 2023 Rafał Safin (rafsaf). All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# Generated by Django 4.0.3 on 2022-04-03 21:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0038_targetvertex_points_weightmaximum_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeProduct",
            fields=[
                (
                    "product_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("active", models.BooleanField()),
                ("name", models.CharField(max_length=512)),
                ("updated", models.IntegerField()),
                ("created", models.IntegerField()),
                (
                    "months",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StripePrice",
            fields=[
                (
                    "price_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("active", models.BooleanField()),
                ("created", models.IntegerField()),
                ("amount", models.IntegerField()),
                ("currency", models.CharField(max_length=3)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.stripeproduct",
                    ),
                ),
            ],
        ),
    ]
