# Generated by Django 4.0.3 on 2022-04-03 21:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0038_targetvertex_points_weightmaximum_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeProduct",
            fields=[
                (
                    "product_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("active", models.BooleanField()),
                ("name", models.CharField(max_length=512)),
                ("updated", models.IntegerField()),
                ("created", models.IntegerField()),
                (
                    "months",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StripePrice",
            fields=[
                (
                    "price_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("active", models.BooleanField()),
                ("created", models.IntegerField()),
                ("amount", models.IntegerField()),
                ("currency", models.CharField(max_length=3)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.stripeproduct",
                    ),
                ),
            ],
        ),
    ]
