# Generated by Django 4.0.3 on 2022-04-03 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_targetvertex_points_weightmaximum_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeProduct',
            fields=[
                ('product_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
                ('name', models.CharField(max_length=512)),
                ('updated', models.IntegerField()),
                ('months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
