# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 4.0.2 on 2022-04-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0041_stripeprice_unique price"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="PLN", max_length=3),
        ),
    ]
