# Generated by Django 4.0.3 on 2022-04-06 04:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0045_alter_stripeprice_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stripeprice",
            options={"ordering": ["currency", "-active", "amount"]},
        ),
    ]
