# Generated by Django 4.0.3 on 2022-04-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0046_alter_stripeprice_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="world",
            name="speed_units",
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name="world",
            name="speed_world",
            field=models.FloatField(blank=True, default=1),
        ),
    ]
