# Generated by Django 4.0.3 on 2022-04-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0046_alter_stripeprice_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="amount_pln",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="payment",
            name="exchange_rate",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="fee_pln",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_intent_id",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]
