# Generated by Django 4.0.4 on 2022-04-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0050_alter_pdfpaymentsummary_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="world",
            name="speed_units",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="world",
            name="speed_world",
            field=models.FloatField(default=1),
        ),
    ]
