# Copyright 2023 Rafał Safin (rafsaf). All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# Generated by Django 4.0.4 on 2022-04-25 23:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0051_alter_world_speed_units_alter_world_speed_world"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pdfpaymentsummary",
            options={
                "verbose_name": "PDF Summary",
                "verbose_name_plural": "PDF Summaries",
            },
        ),
        migrations.AlterModelOptions(
            name="stats",
            options={"verbose_name": "Statistic", "verbose_name_plural": "Statistics"},
        ),
        migrations.AlterModelOptions(
            name="targetvertex",
            options={"verbose_name": "Target", "verbose_name_plural": "Targets"},
        ),
    ]
