# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 4.0.4 on 2022-04-25 23:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0052_alter_pdfpaymentsummary_options_alter_stats_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weightmodel",
            name="t1",
        ),
        migrations.RemoveField(
            model_name="weightmodel",
            name="t2",
        ),
    ]
