# Generated by Django 4.0.4 on 2022-04-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0053_remove_weightmodel_t1_remove_weightmodel_t2"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightmodel",
            name="t1",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="weightmodel",
            name="t2",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
