# Copyright 2023 Rafał Safin (rafsaf). All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# Generated by Django 4.0.4 on 2022-05-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0054_remove_world_etag_player_remove_world_etag_tribe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="deff_troops_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="outline",
            name="deff_troops_weightmodels_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="outline",
            name="off_troops_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="outline",
            name="off_troops_weightmodels_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
