# Generated by Django 4.0.4 on 2022-05-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0054_remove_world_etag_player_remove_world_etag_tribe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="deff_troops_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="outline",
            name="deff_troops_weightmodels_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="outline",
            name="off_troops_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="outline",
            name="off_troops_weightmodels_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
