# Copyright 2023 Rafał Safin (rafsaf). All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# Generated by Django 4.0.4 on 2022-06-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0055_outline_deff_troops_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outline",
            name="initial_outline_catapult_default",
            field=models.IntegerField(
                choices=[
                    (25, "25"),
                    (50, "50"),
                    (75, "75"),
                    (100, "100"),
                    (150, "150"),
                    (200, "200"),
                ],
                default=50,
            ),
        ),
    ]
