# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 4.0.4 on 2022-06-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0055_outline_deff_troops_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outline",
            name="initial_outline_catapult_default",
            field=models.IntegerField(
                choices=[
                    (25, "25"),
                    (50, "50"),
                    (75, "75"),
                    (100, "100"),
                    (150, "150"),
                    (200, "200"),
                ],
                default=50,
            ),
        ),
    ]
