# Generated by Django 4.0.5 on 2022-06-30 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0056_alter_outline_initial_outline_catapult_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="initial_outline_maximum_off_dist",
            field=models.IntegerField(
                default=100,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="outline",
            name="initial_outline_maximum_front_dist",
            field=models.IntegerField(
                default=80,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
    ]
