# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 4.0.5 on 2022-07-03 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0057_outline_initial_outline_maximum_off_dist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outline",
            name="filter_targets_number",
            field=models.IntegerField(
                default=25,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(200),
                ],
            ),
        ),
    ]
