# Generated by Django 4.1.2 on 2022-11-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0058_alter_outline_filter_targets_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="input_data_type",
            field=models.CharField(
                choices=[
                    ("Army collection", "Army collection"),
                    ("Deff collection", "Deff collection"),
                ],
                default="Army collection",
                max_length=32,
            ),
        ),
    ]
