# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 4.1.2 on 2022-11-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0059_outline_input_data_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="input_data_type",
            field=models.CharField(
                choices=[
                    ("Army collection", "Army collection"),
                    ("Deff collection", "Deff collection"),
                ],
                default="Army collection",
                max_length=32,
            ),
        ),
    ]
