# Generated by Django 4.0.4 on 2022-06-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0059_troopshistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="troopshistory",
            options={
                "verbose_name": "Troops History",
                "verbose_name_plural": "Troops Histories",
            },
        ),
    ]
