# Generated by Django 4.1.4 on 2022-12-20 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0064_outline_send_message_with_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="filter_weights_nobles_min",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
