# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 4.1.7 on 2023-03-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0066_alter_message_id_alter_outline_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutlineWriteLock",
            fields=[
                (
                    "outline_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("lock_expire", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
