# Copyright 2023 Rafał Safin (rafsaf). All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# Generated by Django 4.1.7 on 2023-03-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0066_alter_message_id_alter_outline_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutlineWriteLock",
            fields=[
                (
                    "outline_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("lock_expire", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
