# Generated by Django 4.1.7 on 2023-03-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0067_outlinewritelock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outlinewritelock",
            name="lock_expire",
            field=models.DateTimeField(db_index=True),
        ),
    ]
