# Copyright 2023 Rafał Safin (rafsaf). All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# Generated by Django 4.1.7 on 2023-03-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0068_alter_outlinewritelock_lock_expire"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="send_message_text_message",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="profile",
            name="send_message_title_message",
            field=models.CharField(default="Outline Targets", max_length=200),
        ),
    ]
