# Generated by Django 4.1.7 on 2023-03-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0068_alter_outlinewritelock_lock_expire"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="send_message_text_message",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="profile",
            name="send_message_title_message",
            field=models.CharField(default="Outline Targets", max_length=200),
        ),
    ]
