# Generated by Django 4.2.4 on 2023-08-31 17:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0070_alter_server_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="available_catapults",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                max_length=4,
                size=None,
            ),
        ),
    ]
