# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 4.2.4 on 2023-08-31 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0071_outline_available_catapults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outline",
            name="initial_outline_target_dist",
            field=models.IntegerField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="world",
            name="max_noble_distance",
            field=models.IntegerField(default=500),
        ),
    ]
