# Generated by Django 4.2.5 on 2023-09-28 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0072_alter_outline_initial_outline_target_dist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="initial_outline_max_nobles_from_one_village",
            field=models.IntegerField(
                default=16,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(250),
                ],
            ),
        ),
        migrations.AddField(
            model_name="outline",
            name="initial_outline_minimum_noble_troops",
            field=models.IntegerField(
                default=100,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(28000),
                ],
            ),
        ),
    ]
