# Generated by Django 4.2.6 on 2023-11-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0072_alter_outline_initial_outline_target_dist_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outline",
            old_name="initial_outline_catapult_default",
            new_name="initial_outline_catapult_max_value",
        ),
        migrations.AddField(
            model_name="outline",
            name="initial_outline_catapult_min_value",
            field=models.IntegerField(
                choices=[
                    (25, "25"),
                    (50, "50"),
                    (75, "75"),
                    (100, "100"),
                    (150, "150"),
                    (200, "200"),
                ],
                default=25,
            ),
        ),
        migrations.AlterField(
            model_name="outline",
            name="initial_outline_catapult_max_value",
            field=models.IntegerField(
                choices=[
                    (25, "25"),
                    (50, "50"),
                    (75, "75"),
                    (100, "100"),
                    (150, "150"),
                    (200, "200"),
                ],
                default=200,
            ),
        ),
    ]
