# Generated by Django 4.2.6 on 2023-11-01 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "base",
            "0073_rename_initial_outline_catapult_default_outline_initial_outline_catapult_max_value_and_more_squashed_0074_alter_outline_initial_outline_catapult_max_value",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="initial_outline_nobles_limit",
            field=models.IntegerField(
                default=16,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(250),
                ],
            ),
        ),
        migrations.AddField(
            model_name="outline",
            name="initial_outline_minimum_noble_troops",
            field=models.IntegerField(
                default=100,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(28000),
                ],
            ),
        ),
    ]
