# Generated by Django 4.2.6 on 2023-11-01 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0075_outline_initial_outline_max_nobles_from_one_village_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightmaximum",
            name="nobles_limit",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(250),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="outline",
            name="initial_outline_nobles_limit",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(250),
                ],
            ),
        ),
    ]
