# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 4.2.7 on 2023-11-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0077_rename_last_update_world_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="overview",
            name="new_extended",
            field=models.TextField(default=""),
        ),
    ]
