# Generated by Django 4.2.7 on 2023-11-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0078_overview_new_extended"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outline",
            name="sending_option",
            field=models.CharField(
                choices=[
                    ("default", "(Default) Auto generated, fully equipped safe links"),
                    ("string", "Text simple directly in message"),
                    ("new_extended", "New text extended directly in message"),
                    ("extended", "Old text extended directly in message"),
                    ("deputy", "Text for deputy directly in message"),
                ],
                default="default",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="sending_option",
            field=models.CharField(
                choices=[
                    ("default", "(Default) Auto generated, fully equipped safe links"),
                    ("string", "Text simple directly in message"),
                    ("new_extended", "New text extended directly in message"),
                    ("extended", "Old text extended directly in message"),
                    ("deputy", "Text for deputy directly in message"),
                ],
                default="default",
                max_length=50,
            ),
        ),
    ]
