# Copyright 2023 Rafał Safin (rafsaf). All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# Generated by Django 5.0 on 2024-01-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0079_alter_outline_sending_option_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="world",
            name="casual_attack_block_ratio",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
