# Generated by Django 5.0.1 on 2024-01-08 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0080_world_casual_attack_block_ratio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outline",
            name="initial_outline_minimum_noble_troops",
            field=models.IntegerField(
                default=100,
                validators=[
                    django.core.validators.MinValueValidator(20),
                    django.core.validators.MaxValueValidator(28000),
                ],
            ),
        ),
    ]
