# Generated by Django 5.0.1 on 2024-02-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0082_outline_deff_collection_text_enroute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outlinewritelock",
            name="lock_name",
            field=models.CharField(default="write_outline", max_length=64),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="outlinewritelock",
            constraint=models.UniqueConstraint(
                fields=("outline_id", "lock_name"),
                name="unique_lock_by_outline_and_name",
            ),
        ),
    ]
