# Generated by Django 5.0.6 on 2024-07-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0084_alter_outline_initial_outline_minimum_noble_troops"),
    ]

    operations = [
        migrations.AddField(
            model_name="world",
            name="pending_delete",
            field=models.BooleanField(default=False),
        ),
    ]
