# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 5.0.6 on 2024-09-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0085_world_pending_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="periodmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("all", "All (left)"),
                    ("random", "Random"),
                    ("exact", "Exact"),
                ],
                max_length=15,
            ),
        ),
    ]
