# Copyright 2024 Rafał Safin (rafsaf). All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# Generated by Django 5.1.2 on 2024-10-12 11:52

from django.db import migrations, models


def payment_update_mail_sent_true(apps, schema_editor) -> None:
    Payment = apps.get_model("base", "Payment")
    Payment.objects.update(mail_sent=True)


def payment_update_mail_sent_true_reverse(apps, schema_editor) -> None:
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0088_world_full_game_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="mail_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            code=payment_update_mail_sent_true,
            reverse_code=payment_update_mail_sent_true_reverse,
            atomic=True,
        ),
    ]
