# Generated by Django 5.1.2 on 2024-10-12 11:52

from django.db import migrations, models


def payment_update_mail_sent_true(apps, schema_editor) -> None:
    Payment = apps.get_model("base", "Payment")
    Payment.objects.update(mail_sent=True)


def payment_update_mail_sent_true_reverse(apps, schema_editor) -> None:
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0088_world_full_game_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="mail_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            code=payment_update_mail_sent_true,
            reverse_code=payment_update_mail_sent_true_reverse,
            atomic=True,
        ),
    ]
