# Generated by Django 5.1.2 on 2024-11-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0089_payment_mail_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="outlineoverview",
            name="outline_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="outlineoverview",
            name="world_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
