# Generated by Django 5.1.2 on 2024-11-11 15:59

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0090_outlineoverview_outline_json_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outlineoverview",
            name="outline_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="outlineoverview",
            name="world_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
