# Generated by Django 5.1.2 on 2024-11-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0091_alter_outlineoverview_outline_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetvertex",
            name="player_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="targetvertex",
            name="village_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weightmaximum",
            name="player_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weightmaximum",
            name="village_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weightmodel",
            name="player_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weightmodel",
            name="village_id",
            field=models.IntegerField(default=0),
        ),
    ]
