# Copyright 2025 Rafał Safin (rafsaf). All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# Generated by Django 5.1.2 on 2024-11-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0091_alter_outlineoverview_outline_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetvertex",
            name="player_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="targetvertex",
            name="village_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weightmaximum",
            name="player_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weightmaximum",
            name="village_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weightmodel",
            name="player_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weightmodel",
            name="village_id",
            field=models.IntegerField(default=0),
        ),
    ]
