# Generated by Django 5.1.2 on 2024-12-15 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0093_server_tz"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="initial_outline_ruins_max_off",
            field=models.IntegerField(
                default=28000,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(28000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="outline",
            name="initial_outline_ruins_min_off",
            field=models.IntegerField(
                default=19000,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(28000),
                ],
            ),
        ),
    ]
