# Generated by Django 5.1.2 on 2024-12-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0094_outline_parent_outline_alter_outline_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outline",
            name="name",
            field=models.CharField(max_length=24),
        ),
    ]
