# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 5.1.2 on 2024-12-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0095_alter_outline_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="stats",
            name="outline_duplicated",
            field=models.IntegerField(default=0),
        ),
    ]
