# Generated by Django 5.1.6 on 2025-03-10 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0096_stats_outline_duplicated"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="initial_outline_minimum_fake_noble_troops",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(28000),
                ],
            ),
        ),
    ]
