# Generated by Django 5.1.8 on 2025-04-13 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0098_remove_weightmaximum_fake_limit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outline",
            name="initial_outline_minimum_fake_noble_troops",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(200),
                ],
            ),
        ),
    ]
