# Copyright 2025 Rafał Safin (rafsaf). All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# Generated by Django 5.1.8 on 2025-04-13 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0099_alter_outline_initial_outline_minimum_fake_noble_troops"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outline",
            old_name="avaiable_nobles",
            new_name="available_nobles",
        ),
        migrations.RenameField(
            model_name="outline",
            old_name="avaiable_nobles_near",
            new_name="available_nobles_near",
        ),
        migrations.RenameField(
            model_name="outline",
            old_name="avaiable_offs",
            new_name="available_offs",
        ),
        migrations.RenameField(
            model_name="outline",
            old_name="avaiable_offs_near",
            new_name="available_offs_near",
        ),
        migrations.RenameField(
            model_name="outline",
            old_name="avaiable_ruins",
            new_name="available_ruins",
        ),
    ]
