# Generated by Django 5.1.8 on 2025-04-13 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0099_alter_outline_initial_outline_minimum_fake_noble_troops"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outline",
            old_name="avaiable_nobles",
            new_name="available_nobles",
        ),
        migrations.RenameField(
            model_name="outline",
            old_name="avaiable_nobles_near",
            new_name="available_nobles_near",
        ),
        migrations.RenameField(
            model_name="outline",
            old_name="avaiable_offs",
            new_name="available_offs",
        ),
        migrations.RenameField(
            model_name="outline",
            old_name="avaiable_offs_near",
            new_name="available_offs_near",
        ),
        migrations.RenameField(
            model_name="outline",
            old_name="avaiable_ruins",
            new_name="available_ruins",
        ),
    ]
