# Generated by Django 5.1.8 on 2025-04-13 13:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0100_rename_avaiable_nobles_outline_available_nobles_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="available_full_noble_offs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                max_length=4,
                size=None,
            ),
        ),
    ]
