# Generated by Django 5.1.8 on 2025-04-13 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0101_outline_available_full_noble_offs"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="initial_outline_min_ruin_attack_off",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(28000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="outline",
            name="initial_outline_ruin_full_offs_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
