# Generated by Django 5.1.8 on 2025-04-13 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0102_outline_initial_outline_min_ruin_attack_off_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outline",
            name="initial_outline_ruin_full_offs_enabled",
        ),
    ]
