# Copyright 2025 Rafał Safin (rafsaf). All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# Generated by Django 5.1.8 on 2025-04-13 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0102_outline_initial_outline_min_ruin_attack_off_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outline",
            name="initial_outline_ruin_full_offs_enabled",
        ),
    ]
