# Generated by Django 5.1.8 on 2025-04-20 22:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0104_remove_outline_initial_outline_off_left_catapult"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="targetvertex",
            name="enter_t1",
        ),
        migrations.RemoveField(
            model_name="targetvertex",
            name="enter_t2",
        ),
        migrations.RemoveField(
            model_name="targetvertex",
            name="night_bonus",
        ),
    ]
