# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 5.1.8 on 2025-05-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0105_remove_targetvertex_enter_t1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="feature_flag_shipments",
            field=models.BooleanField(default=False),
        ),
    ]
