# Generated by Django 5.2.6 on 2025-09-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0108_payment_created_at_payment_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("pl", "Polish"), ("hu", "Hungarian")],
                default="en",
                max_length=16,
            ),
        ),
    ]
