# Generated by Django 5.2.6 on 2025-09-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0109_alter_payment_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("pl", "Polish"),
                    ("hu", "Hungarian"),
                    ("pt-br", "Português (Brasil)"),
                ],
                default="en",
                max_length=16,
            ),
        ),
    ]
