# Generated by Django 5.2.6 on 2025-09-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0111_alter_payment_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="currency",
        ),
        migrations.AddField(
            model_name="profile",
            name="user_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PLN", "PLN"),
                    ("EUR", "EUR"),
                    ("HUF", "HUF"),
                    ("BRL", "BRL"),
                    ("CZK", "CZK"),
                ],
                default=None,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[
                    ("PLN", "PLN"),
                    ("EUR", "EUR"),
                    ("HUF", "HUF"),
                    ("BRL", "BRL"),
                    ("CZK", "CZK"),
                ],
                default="PLN",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="stripeprice",
            name="currency",
            field=models.CharField(
                choices=[
                    ("PLN", "PLN"),
                    ("EUR", "EUR"),
                    ("HUF", "HUF"),
                    ("BRL", "BRL"),
                    ("CZK", "CZK"),
                ],
                max_length=3,
            ),
        ),
    ]
