# Copyright 2025 Rafał Safin (rafsaf). All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# Generated by Django 5.2.6 on 2025-09-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0111_alter_payment_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="currency",
        ),
        migrations.AddField(
            model_name="profile",
            name="user_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PLN", "PLN"),
                    ("EUR", "EUR"),
                    ("HUF", "HUF"),
                    ("BRL", "BRL"),
                    ("CZK", "CZK"),
                ],
                default=None,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[
                    ("PLN", "PLN"),
                    ("EUR", "EUR"),
                    ("HUF", "HUF"),
                    ("BRL", "BRL"),
                    ("CZK", "CZK"),
                ],
                default="PLN",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="stripeprice",
            name="currency",
            field=models.CharField(
                choices=[
                    ("PLN", "PLN"),
                    ("EUR", "EUR"),
                    ("HUF", "HUF"),
                    ("BRL", "BRL"),
                    ("CZK", "CZK"),
                ],
                max_length=3,
            ),
        ),
    ]
