# Generated by Django 5.2.6 on 2025-09-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0112_remove_profile_currency_profile_user_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("pl", "Polish"),
                    ("hu", "Hungarian"),
                    ("pt-br", "Português (Brasil)"),
                    ("cs", "Czech"),
                    ("de", "German"),
                ],
                default="en",
                max_length=16,
            ),
        ),
    ]
