# Generated by Django 5.2.6 on 2025-09-27 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0113_alter_payment_language"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stripeprice",
            name="unique price",
        ),
    ]
