# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 5.2.6 on 2025-09-27 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0113_alter_payment_language"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stripeprice",
            name="unique price",
        ),
    ]
