# Generated by Django 5.2.7 on 2025-11-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0114_remove_stripeprice_unique_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outlinewritelock",
            name="outline_id",
            field=models.BigIntegerField(),
        ),
        migrations.AddField(
            model_name="outlinewritelock",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
