# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 5.2.7 on 2025-11-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0115_outlinewritelock_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outlinewritelock",
            name="outline_id",
            field=models.BigIntegerField(db_index=True),
        ),
    ]
