# Generated by Django 5.2.7 on 2025-11-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0115_outlinewritelock_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outlinewritelock",
            name="outline_id",
            field=models.BigIntegerField(db_index=True),
        ),
    ]
