# Copyright 2025 Rafał Safin (rafsaf). All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# Generated by Django 5.2.8 on 2025-11-19 19:56

from django.db import migrations, models

import utils.buildings


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0116_alter_outlinewritelock_outline_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weightmodel",
            name="building",
            field=models.CharField(
                blank=True,
                choices=[
                    ("headquarters", "Headquarters"),
                    ("barracks", "Barracks"),
                    ("stable", "Stable"),
                    ("workshop", "Workshop"),
                    ("academy", "Academy"),
                    ("smithy", "Smithy"),
                    ("rally_point", "Rally point"),
                    ("statue", "Statue"),
                    ("market", "Market"),
                    (utils.buildings.BUILDING["TIMBER_CAMP"], "Timber camp"),
                    (utils.buildings.BUILDING["CLAY_PIT"], "Clay pit"),
                    (utils.buildings.BUILDING["IRON_MINE"], "Iron mine"),
                    (utils.buildings.BUILDING["FARM"], "Farm"),
                    (utils.buildings.BUILDING["WAREHOUSE"], "Warehouse"),
                    (utils.buildings.BUILDING["WALL"], "Wall"),
                    (utils.buildings.BUILDING["WATCHTOWER"], "Watchtower"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weightmodel",
            name="catapult",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="weightmodel",
            name="first_line",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="weightmodel",
            name="player_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="weightmodel",
            name="ruin",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="weightmodel",
            name="village_id",
            field=models.IntegerField(),
        ),
    ]
