# Generated by Django 5.2.8 on 2025-12-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0117_alter_weightmodel_building_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outline",
            name="sending_option",
            field=models.CharField(
                choices=[
                    ("default", "(Default) Auto generated, fully equipped safe links"),
                    ("new_extended", "Standard text directly in message"),
                    ("deputy", "Standard text for deputy directly in message"),
                    ("string", "Simple text directly in message"),
                    ("extended", "Old text directly in message"),
                    ("table", "Table directly in message"),
                ],
                default="default",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="sending_option",
            field=models.CharField(
                choices=[
                    ("default", "(Default) Auto generated, fully equipped safe links"),
                    ("new_extended", "Standard text directly in message"),
                    ("deputy", "Standard text for deputy directly in message"),
                    ("string", "Simple text directly in message"),
                    ("extended", "Old text directly in message"),
                    ("table", "Table directly in message"),
                ],
                default="default",
                max_length=50,
            ),
        ),
    ]
