# Generated by Django 5.2.8 on 2025-12-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0118_alter_outline_sending_option_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightmaximum",
            name="ram_left",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="weightmaximum",
            name="ram_max",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="weightmaximum",
            name="ram_state",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
