# Copyright: (c) 2020-2026, Rafał Safin <rafal.safin@rafsaf.pl>
# GNU Affero General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/agpl-3.0.txt)

# Generated by Django 5.2.8 on 2025-12-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0119_weightmaximum_ram_left_weightmaximum_ram_max_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weightmaximum",
            name="ram_state",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
