# Generated by Django 6.0.2 on 2026-02-26 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0120_alter_weightmaximum_ram_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="messages",
        ),
    ]
