# Generated by Django 6.0.2 on 2026-02-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0121_remove_profile_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weightmaximum",
            name="ram_left",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="weightmaximum",
            name="ram_max",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="weightmaximum",
            name="ram_state",
            field=models.IntegerField(default=0),
        ),
    ]
