# Generated by Django 6.0.4 on 2026-04-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0122_alter_weightmaximum_ram_left_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetvertex",
            name="deff_noble_order",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="targetvertex",
            name="has_deff_noble",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="weightmaximum",
            name="deff_left",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weightmaximum",
            name="deff_max",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weightmaximum",
            name="deff_state",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weightmodel",
            name="deff",
            field=models.IntegerField(default=0),
        ),
    ]
