# Generated by Django 6.1 on 2026-08-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0122_alter_weightmaximum_ram_left_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
