# Generated by Django 6.1 on 2026-08-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0123_profile_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="deleted_at_exp",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
