# Generated by Django 6.0.4 on 2026-04-25 17:10

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0123_targetvertex_deff_noble_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="filter_weights_deff_max",
            field=models.IntegerField(
                default=30000,
                validators=[MinValueValidator(0), MaxValueValidator(30000)],
            ),
        ),
        migrations.AddField(
            model_name="outline",
            name="filter_weights_deff_min",
            field=models.IntegerField(
                default=0,
                validators=[MinValueValidator(0), MaxValueValidator(30000)],
            ),
        ),
    ]
