# Generated by Django 6.0.4 on 2026-04-25 17:42

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0124_outline_filter_weights_deff_min_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="available_deff_noble_villages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=4,
            ),
        ),
        migrations.AddField(
            model_name="outline",
            name="initial_outline_max_deff",
            field=models.IntegerField(
                default=28000,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(28000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="outline",
            name="initial_outline_min_deff",
            field=models.IntegerField(
                default=15000,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(28000),
                ],
            ),
        ),
    ]
