# Generated by Django 6.1.1 on 2026-09-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0124_profile_deleted_at_exp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="world",
            name="full_game_name",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
