# Generated by Django 6.1 on 2026-08-30 12:06

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0124_profile_deleted_at_exp"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="available_deff_noble_villages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, max_length=4
            ),
        ),
        migrations.AddField(
            model_name="outline",
            name="filter_weights_deff_max",
            field=models.IntegerField(
                default=30000,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(30000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="outline",
            name="filter_weights_deff_min",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(30000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="outline",
            name="initial_outline_max_deff",
            field=models.IntegerField(
                default=28000,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(28000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="outline",
            name="initial_outline_min_deff",
            field=models.IntegerField(
                default=15000,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(28000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="targetvertex",
            name="deff_noble_order",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="targetvertex",
            name="has_deff_noble",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="weightmaximum",
            name="deff_left",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weightmaximum",
            name="deff_max",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weightmaximum",
            name="deff_state",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weightmodel",
            name="deff",
            field=models.IntegerField(default=0),
        ),
    ]
