# Generated by Django 6.1.1 on 2026-10-03 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0127_remove_outline_initial_outline_average_ruining_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outline",
            name="initial_outline_catapult_min_value",
            field=models.IntegerField(
                default=25,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1175),
                ],
            ),
        ),
    ]
