name: "Setup Python and uv Environment"
description: "Checks out code, sets up Python, installs uv, and caches/installs dependencies."
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.9.2"
        enable-cache: true

    - name: Install the project
      run: uv sync --locked --all-extras --dev
      shell: bash
