name: Manual triggers for server actions

permissions: {}

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action on server"
        required: true
        type: choice
        default: "redeploy"
        options:
          - "redeploy"
          - "restart"
          - "reboot"
      environment:
        description: "Target environment"
        required: true
        type: choice
        default: "prod"
        options:
          - "dev"
          - "prod"
          - "stage"

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger prod server - ${{ github.event.inputs.action }}
        if: ${{ github.event.inputs.environment == 'prod' }}
        run: |
          curl -k -X POST https://${{ secrets.PROD_HOOK_IP }}:9000/hooks/${{ github.event.inputs.action }} -H "Content-Type: application/json" -d '{"secret": "${{ secrets.PROD_HOOK_SECRET }}"}'

      - name: Trigger stage server - ${{ github.event.inputs.action }}
        if: ${{ github.event.inputs.environment == 'stage' }}
        run: |
          curl -k -X POST https://${{ secrets.STAGE_HOOK_IP }}:9000/hooks/${{ github.event.inputs.action }} -H "Content-Type: application/json" -d '{"secret": "${{ secrets.STAGE_HOOK_SECRET }}"}'

      - name: Trigger dev server - ${{ github.event.inputs.action }}
        if: ${{ github.event.inputs.environment == 'dev' }}
        run: |
          curl -k -X POST https://${{ secrets.DEV_HOOK_IP }}:9000/hooks/${{ github.event.inputs.action }} -H "Content-Type: application/json" -d '{"secret": "${{ secrets.DEV_HOOK_SECRET }}"}' --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40
